# Generated by Django 4.2.4 on 2023-10-27 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='income',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='savings',
        ),
        migrations.AlterField(
            model_name='profiles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
