# Generated by Django 4.2.6 on 2023-10-28 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='income',
            name='profile',
            field=models.ForeignKey(default=list, on_delete=django.db.models.deletion.PROTECT, to='profiles.profiles'),
        ),
        migrations.AddField(
            model_name='goals',
            name='profile',
            field=models.ForeignKey(default=list, on_delete=django.db.models.deletion.PROTECT, to='profiles.profiles'),
        ),
        migrations.AddField(
            model_name='expense',
            name='profile',
            field=models.ForeignKey(default=list, on_delete=django.db.models.deletion.PROTECT, to='profiles.profiles'),
        ),
    ]
