# Generated by Django 4.2.6 on 2023-10-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('Savings', 'Savings Account'), ('Checking', 'Checking Account'), ('Investment', 'Investment Account'), ('Loan', 'Loan Account')], default='Savings', max_length=50, verbose_name='Account Type'),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(default=30, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='user',
            name='credit_card_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True, verbose_name='Credit Card Limit'),
        ),
        migrations.AddField(
            model_name='user',
            name='dependents',
            field=models.PositiveIntegerField(default=3, verbose_name='Dependents'),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_type',
            field=models.CharField(choices=[('Salaried', 'Salaried'), ('Self-Employed', 'Self-Employed'), ('Business Owner', 'Business Owner')], default='Salaried', max_length=50, verbose_name='Employment Type'),
        ),
        migrations.AddField(
            model_name='user',
            name='fixed_deposit_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True, verbose_name='Fixed Deposit Balance'),
        ),
        migrations.AddField(
            model_name='user',
            name='loan_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Loan Balance'),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monthly Deposit'),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Monthly Expenses'),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Monthly Income'),
        ),
        migrations.AddField(
            model_name='user',
            name='mortgage_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True, verbose_name='Mortgage Balance'),
        ),
        migrations.AddField(
            model_name='user',
            name='risk_tolerance',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20, verbose_name='Risk Tolerance'),
        ),
        migrations.AddField(
            model_name='user',
            name='savings_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Savings Balance'),
        ),
        migrations.AddField(
            model_name='user',
            name='spending_pattern',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=20, verbose_name='Spending Pattern'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Country'),
        ),
    ]
