# Generated by Django 4.2.6 on 2023-10-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_account_type_user_age_user_credit_card_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_records',
            field=models.JSONField(default=list, verbose_name='Chat Records'),
        ),
    ]
