# Generated by Django 4.2.6 on 2023-10-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_chat_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.CharField(choices=[('married', 'married'), ('single', 'single'), ('divorced', 'divorced')], default='single', max_length=50, verbose_name='Marital Status'),
        ),
    ]
