# Generated by Django 4.2.6 on 2023-10-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_marital_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dependents',
        ),
        migrations.AddField(
            model_name='user',
            name='dependants',
            field=models.PositiveIntegerField(default=3, verbose_name='Dependants'),
        ),
    ]
