# Generated by Django 4.2.6 on 2023-10-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_dependents_user_dependants'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='loan',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Personal Loan'),
        ),
    ]
