# Generated by Django 4.2.6 on 2023-10-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_default_user_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='risk_tolerance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='spending_pattern',
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_fund_bal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Personal Loan'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True, verbose_name='Gender'),
        ),
    ]
