from django.urls import path
from apps.profiles.views import (
    IncomeList,
    IncomeDetail,
    ExpenseList,
    ExpenseDetail,
    SavingsList,
    SavingsDetail,
    GoalsList,
    GoalsDetail,
    ProfilesList,
    ProfilesDetail,
)

urlpatterns = [
    path('profile',
         ProfilesList.as_view(),
         name='profiles-list'),
    path('profile/<str:pk>/',
         ProfilesDetail.as_view(),
         name='profiles-detail'),
    path('income',
         IncomeList.as_view(),
         name='income-list'),
    path('income/<str:pk>/',
         IncomeDetail.as_view(),
         name='income-detail'),
    path('expense',
         ExpenseList.as_view(),
         name='expense-list'),
    path('expense/<str:pk>/',
         ExpenseDetail.as_view(),
         name='expense-detail'),
    path('savings',
         SavingsList.as_view(),
         name='savings-list'),
    path('savings/<str:pk>/',
         SavingsDetail.as_view(),
         name='savings-detail'),
    path('goals',
         GoalsList.as_view(),
         name='goals-list'),
    path('goals/<str:pk>/',
         GoalsDetail.as_view(),
         name='goals-detail'),
]